title:              RYANKSMITH.NET
email:              me@ryanksmith.net
description:        A Personal and Technical Blog
author:             Ryan Smith
baseurl:            "/"
url:                "https://www.ryanksmith.net"

# Social Profiles
twitter_username:   cyb3rp00l
github_username:    PacketGimp
facebook_username:  cybersecradar
linkedin_username:  cybersecradar

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-154442289-1

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site