theme: jekyll-theme-clean-blog

title:              Ryan K. Smith
email:              me@ryanksmith.net
description:        A Blog Theme by Start Bootstrap
author:             Ryan K. Smith
baseurl:            "/ryanksmith1.github.io/"
url:                "https://packetgimp.github.io/"

# Social Profiles
twitter_username:   cyb3rp00l
github_username:    PacketGimp
facebook_username:  cyb3rp00l
linkedin_username:  cyb3rp00l

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
